# https://goreleaser.com/customization/build/
builds:
  - main: ./cmd/containerdbg
    ldflags:
    - -extldflags -static -s -w
    env:
    - CGO_ENABLED=0
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs[(\\w)]*:+.*$'
    - '^test[(\\w)]*:+.*$'
