// Copyright 2022 Google LLC All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: node_api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MonitorPodResponse_ErrorCode int32

const (
	MonitorPodResponse_OK      MonitorPodResponse_ErrorCode = 0
	MonitorPodResponse_UNKNOWN MonitorPodResponse_ErrorCode = 1
)

// Enum value maps for MonitorPodResponse_ErrorCode.
var (
	MonitorPodResponse_ErrorCode_name = map[int32]string{
		0: "OK",
		1: "UNKNOWN",
	}
	MonitorPodResponse_ErrorCode_value = map[string]int32{
		"OK":      0,
		"UNKNOWN": 1,
	}
)

func (x MonitorPodResponse_ErrorCode) Enum() *MonitorPodResponse_ErrorCode {
	p := new(MonitorPodResponse_ErrorCode)
	*p = x
	return p
}

func (x MonitorPodResponse_ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MonitorPodResponse_ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_node_api_proto_enumTypes[0].Descriptor()
}

func (MonitorPodResponse_ErrorCode) Type() protoreflect.EnumType {
	return &file_node_api_proto_enumTypes[0]
}

func (x MonitorPodResponse_ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MonitorPodResponse_ErrorCode.Descriptor instead.
func (MonitorPodResponse_ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_node_api_proto_rawDescGZIP(), []int{1, 0}
}

type MonitorPodRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *SourceId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *MonitorPodRequest) Reset() {
	*x = MonitorPodRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MonitorPodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorPodRequest) ProtoMessage() {}

func (x *MonitorPodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_node_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorPodRequest.ProtoReflect.Descriptor instead.
func (*MonitorPodRequest) Descriptor() ([]byte, []int) {
	return file_node_api_proto_rawDescGZIP(), []int{0}
}

func (x *MonitorPodRequest) GetId() *SourceId {
	if x != nil {
		return x.Id
	}
	return nil
}

type MonitorPodResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code MonitorPodResponse_ErrorCode `protobuf:"varint,1,opt,name=code,proto3,enum=MonitorPodResponse_ErrorCode" json:"code,omitempty"`
}

func (x *MonitorPodResponse) Reset() {
	*x = MonitorPodResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MonitorPodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorPodResponse) ProtoMessage() {}

func (x *MonitorPodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_node_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorPodResponse.ProtoReflect.Descriptor instead.
func (*MonitorPodResponse) Descriptor() ([]byte, []int) {
	return file_node_api_proto_rawDescGZIP(), []int{1}
}

func (x *MonitorPodResponse) GetCode() MonitorPodResponse_ErrorCode {
	if x != nil {
		return x.Code
	}
	return MonitorPodResponse_OK
}

var File_node_api_proto protoreflect.FileDescriptor

var file_node_api_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x0b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a,
	0x11, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x50, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x19, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09,
	0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x22, 0x69, 0x0a,
	0x12, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x50, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1d, 0x2e, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x50, 0x6f, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x20, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x55,
	0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x01, 0x32, 0x47, 0x0a, 0x11, 0x4e, 0x6f, 0x64, 0x65,
	0x44, 0x61, 0x65, 0x6d, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a,
	0x07, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x2e, 0x4d, 0x6f, 0x6e, 0x69, 0x74,
	0x6f, 0x72, 0x50, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x4d,
	0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x50, 0x6f, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x3d, 0x5a, 0x3b, 0x76, 0x65, 0x6c, 0x6f, 0x73, 0x74, 0x72, 0x61, 0x74, 0x61, 0x2d,
	0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x64, 0x62, 0x67, 0x2e, 0x67, 0x69, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_node_api_proto_rawDescOnce sync.Once
	file_node_api_proto_rawDescData = file_node_api_proto_rawDesc
)

func file_node_api_proto_rawDescGZIP() []byte {
	file_node_api_proto_rawDescOnce.Do(func() {
		file_node_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_node_api_proto_rawDescData)
	})
	return file_node_api_proto_rawDescData
}

var file_node_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_node_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_node_api_proto_goTypes = []interface{}{
	(MonitorPodResponse_ErrorCode)(0), // 0: MonitorPodResponse.ErrorCode
	(*MonitorPodRequest)(nil),         // 1: MonitorPodRequest
	(*MonitorPodResponse)(nil),        // 2: MonitorPodResponse
	(*SourceId)(nil),                  // 3: SourceId
}
var file_node_api_proto_depIdxs = []int32{
	3, // 0: MonitorPodRequest.id:type_name -> SourceId
	0, // 1: MonitorPodResponse.code:type_name -> MonitorPodResponse.ErrorCode
	1, // 2: NodeDaemonService.Monitor:input_type -> MonitorPodRequest
	2, // 3: NodeDaemonService.Monitor:output_type -> MonitorPodResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_node_api_proto_init() }
func file_node_api_proto_init() {
	if File_node_api_proto != nil {
		return
	}
	file_event_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_node_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MonitorPodRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_node_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MonitorPodResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_node_api_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_node_api_proto_goTypes,
		DependencyIndexes: file_node_api_proto_depIdxs,
		EnumInfos:         file_node_api_proto_enumTypes,
		MessageInfos:      file_node_api_proto_msgTypes,
	}.Build()
	File_node_api_proto = out.File
	file_node_api_proto_rawDesc = nil
	file_node_api_proto_goTypes = nil
	file_node_api_proto_depIdxs = nil
}
