# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  name: petclinic-postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-postgres
  serviceName: petclinic-postgres
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: petclinic-postgres
    spec:
      containers:
      - env: null
        image: eu.gcr.io/eitane-test/petclinic-postgres:df3658b@sha256:e6dcc041237a27bea6d8fc8303bfda369641c102c82b9d9a90b8e8d4637722b4
        imagePullPolicy: Always
        name: petclinic-postgres
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    migrate-for-anthos-optimization: "true"
    migrate-for-anthos-version: barp-nightly-testing4
  name: petclinic-postgres
  namespace: default
spec:
  ports:
  - name: petclinic-postgres
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: petclinic-postgres
  type: ClusterIP
