on:
  push:
    branches:
    - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19
        check-latest: true
    - name: Set up clang
      uses: egor-tensin/setup-clang@v1
      with:
        version: 13
    - name: Set up libbpf
      run: |
        set -ex
        LIBBPF_VERSION=0.7.0
        
        apt-get -y install libelf-dev
        
        mkdir libbpf
        pushd libbpf
        
        wget https://github.com/libbpf/libbpf/archive/refs/tags/v${LIBBPF_VERSION}.tar.gz
        tar xf v${LIBBPF_VERSION}.tar.gz
        cd libbpf-${LIBBPF_VERSION}/src
        make
        make install
        popd
        rm -rf libbpf
    - uses: supplypike/setup-bin@v1
      name: Install kpt
      with:
        uri: 'https://github.com/GoogleContainerTools/kpt/releases/download/v1.0.0-beta.19/kpt_linux_amd64'
        version: 'v1.0.0-beta.19'
        name: 'kpt'
    - name: test
      run: make test
