on:
  push:
    branches:
    - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19
        check-latest: true
    - uses: supplypike/setup-bin@v1
      name: Install kpt
      with:
        uri: 'https://github.com/GoogleContainerTools/kpt/releases/download/v1.0.0-beta.19/kpt_linux_amd64'
        version: 'v1.0.0-beta.19'
        name: 'kpt'
    - name: test
      run: make test
