name: Update files

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Update files
        uses: MathieuSoysal/file-updater-for-release@v1.0.1
        with:
          files: README.md
          prefix: "containerdbg_"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: update readme"
          title: Update readme
          body: Update readme to reflect release changes
          branch: update-readme
          base: main
