name: goreleaser

on:
  push:
    tags: ['*']

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    outputs:
      hashes: ${{ steps.hash.output.hashes }}
    steps:
    - uses: actions/checkout@v3
    - name: Unshallow
      if: ${{ !env.ACT }}
      run: git fetch --prune --unshallow
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19
        check-latest: true
    - uses: supplypike/setup-bin@v1
      name: Install kpt
      with:
        uri: 'https://github.com/GoogleContainerTools/kpt/releases/download/v1.0.0-beta.19/kpt_linux_amd64'
        version: 'v1.0.0-beta.19'
        name: 'kpt'
    - name: generate
      run: make pre
    - uses: goreleaser/goreleaser-action@v3.1.0
      id: run-goreleaser
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Generate subject
      id: hash
      env:
        ARTIFACTS: "${{ steps.run-goreleaser.outputs.artifacts }}"
      run: |
        set -euo pipefail
        checksum_file=$(echo "$ARTIFACTS" | jq -r '.[] | select (.type=="Checksum") | .path')
        echo "::set-output name=hashes::$(cat $checksum_file | base64 -w0)"
